package modelo;
// Generated 08-may-2015 6:32:48 by Hibernate Tools 4.3.1



/**
 * Cancion generated by hbm2java
 */
public class Cancion  implements java.io.Serializable {


     private int idcancion;
     private String nombrecancion;
     private int idlista;
     private String url;

    public Cancion() {
    }

    public Cancion(int idcancion, String nombrecancion, int idlista, String url) {
       this.idcancion = idcancion;
       this.nombrecancion = nombrecancion;
       this.idlista = idlista;
       this.url = url;
    }
   
    public int getIdcancion() {
        return this.idcancion;
    }
    
    public void setIdcancion(int idcancion) {
        this.idcancion = idcancion;
    }
    public String getNombrecancion() {
        return this.nombrecancion;
    }
    
    public void setNombrecancion(String nombrecancion) {
        this.nombrecancion = nombrecancion;
    }
    public int getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(int idlista) {
        this.idlista = idlista;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


