package modelo;
// Generated 08-may-2015 6:32:48 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombre;
     private String correo;
     private String password;

    public Usuario() {
    }

	
    public Usuario(String nombre, String password) {
        this.nombre = nombre;
        this.password = password;
    }
    public Usuario(String nombre, String correo, String password) {
       this.nombre = nombre;
       this.correo = correo;
       this.password = password;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


